# Basic formatting options that work with stable rustfmt
max_width = 100
tab_spaces = 4
edition = "2021"

# Using only stable options
hard_tabs = false
newline_style = "Auto"
use_small_heuristics = "Default"