# Basic formatting options
max_width = 100
tab_spaces = 4
edition = "2021"

# Trailing commas
trailing_comma = "Vertical"
match_block_trailing_comma = true

# Import formatting
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Function call formatting
fn_params_layout = "Compressed"
where_single_line = true

# Control flow formatting
control_brace_style = "AlwaysSameLine"

# Comment formatting
wrap_comments = true
comment_width = 100
normalize_comments = true